[package]
authors.workspace = true
# categories.workspace = true
# description.workspace = true
edition.workspace = true
# keywords.workspace = true
license.workspace = true
name = "pbt"
readme.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
futures = { version = "~0.3", default-features = false, features = ["alloc"] }
pretty_assertions = "~1.4"
wyrand = { version = "~0.3", default-features = false }

[dev-dependencies]
tokio = { version = "~1.49", features = ["rt", "macros"] }
