[package]
authors.workspace = true
# categories.workspace = true
# description.workspace = true
edition.workspace = true
# keywords.workspace = true
license.workspace = true
name = "pbt-macros"
readme.workspace = true
repository.workspace = true
version.workspace = true


[lib]
proc-macro = true


[dependencies]


[lints]
workspace = true
