[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "pbt-tests"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
pbt = { path = "../pbt" }

[dev-dependencies]
pretty_assertions = "~1.4"

[lints]
workspace = true
